#!/usr/bin/env python

import sys
from epicsscan import get_credentials, create_scandb
cred = get_credentials()
cred.pop('dbname')

name = None
try:
    dnname = sys.argv[1]
except:
    print('create_scandb dbname')
    sys.exit()


print(f"Creating epicsscan {dbname} for user {cred['user']}")
create_scandb(name, **cred)
